#!/bin/sh
set -e

# first arg is `-v` or `--some-option`
if [ "${1#-}" != "$1" ]; then
    set -- ffmpeg "$@"
fi

# live ..
if [ "$1" = 'live' ]; then
    # 至少输入两个参数
    if [ "$#" -lt 3 ]; then
        echo "Usage: live pullStream pushStream [withLogo] [logoWidthPercent] [leftPercent] [topPercent]"
        exit
    fi

    # 是否包含 logo
    if [ -z "$4" ]; then
        withLogo="/usr/local/share/live-logo.png"
    else
        withLogo="$4"
    fi

    # logo 占源视频宽度比例
    if [ -z "$5" ]; then
        logoWidthPercent=25
    else
        logoWidthPercent="$5"
    fi

    # logo 距左侧百分比
    if [ -z "$6" ]; then
        leftPercent=1
    else
        leftPercent="$6"
    fi

    # logo 局顶部百分比
    if [ -z "$7" ]; then
        topPercent=1
    else
        topPercent="$7"
    fi

    pullStream="$2"
    pushStream="$3"

    if [ "${withLogo}" = '0' ]; then
        # 不带 logo
        set -- ffmpeg -stats -re -i "${pullStream}" -vcodec copy -acodec copy -f flv "${pushStream}"
    else
        # 带 logo
        set -- ffmpeg -stats -re -i "${pullStream}" -i "${withLogo}" -filter_complex "[1][0]scale2ref=w='iw*${logoWidthPercent}/100':h='ow/mdar'[wm][vid];[vid][wm]overlay=main_w/100*${leftPercent}:main_h*${topPercent}/100" -vcodec h264 -acodec copy -f flv "${pushStream}"
    fi

    echo "$@"
    echo '------------------------------------------------------------'
fi

exec "$@"
